language: php

# Versions of PHP you want your project run with.
php:
  - 7.1
  - 7.2
  - 7.4
  - 8.0

env:
  - MYSQL_HOST=127.0.0.1 MYSQL_USER=root

services:
  - mysql
  - postgresql

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer require phpstan/phpstan "0.11.3"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ez_test;'
  - mysql -e "CREATE USER ez_test@localhost IDENTIFIED BY 'ezTest'; GRANT ALL ON ez_test.* TO ez_test@localhost; FLUSH PRIVILEGES;"
  - psql -c 'CREATE DATABASE ez_test;' -U postgres
  - psql -c "CREATE USER ez_test WITH PASSWORD 'ezTest';" -U postgres
#  - mysql -e 'GRANT ALL PRIVILEGES ON ez_test.* TO ez_test@localhost;'
#  - mysql -e "SET PASSWORD FOR 'ez_test'@'localhost' = PASSWORD('ezTest')"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis_retry php vendor/bin/php-coveralls

# Commands you want to run that will verify your build.
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpstan analyse lib tests --level=1
